name: Deploy CloudMart Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'cloudformation/**'
      - '.github/workflows/**'
      - 'lambda/**'

  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:

  network:
    name: Deploy Network Stack fifth attempt
    uses: ./.github/workflows/deploy-stack.yaml
    with:
      stack_name: network-stack-CloudMart
      template_file: cloudformation/network-stack.yaml
      parameters_file: cloudformation/config/network-parameters.json
      tags_file: cloudformation/config/tags.json
      environment: dev
    secrets: inherit

  package-lambda:
    name: Package Database Initializer
    needs: network
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Lambda ZIP
        run: |
          mkdir -p lambda-package

          pip install -r lambda/db-initializer/requirements.txt \
            -t lambda-package

          cp lambda/db-initializer/lambda_function.py lambda-package/

          cd lambda-package
          zip -r ../db-initializer.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHubActions-LambdaUpload-${{ github.run_id }}

      - name: Upload Lambda ZIP to S3
        run: |
          aws s3 cp db-initializer.zip \
            s3://${{ vars.LAMBDA_CODE_BUCKET }}/lambda/db-initializer.zip

  data:
    name: Deploy Data Stack
    needs: package-lambda
    uses: ./.github/workflows/deploy-stack.yaml
    with:
      stack_name: data-stack-CloudMart
      template_file: cloudformation/data-stack.yaml
      parameters_file: cloudformation/config/data-parameters.json
      tags_file: cloudformation/config/tags.json
      environment: dev
    secrets: inherit
