name: Deploy CloudMart Infrastructure

on:
  push:
    branches:
      - '**'

  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        default: dev
        type: choice
        options:
        - dev
        - prod

permissions:
  id-token: write
  contents: read

jobs:

  network:
    name: Deploy Network Stacks first
    uses: ./.github/workflows/deploy-stack.yaml
    with:
      stack_name: network-stack-CloudMart version 2
      template_file: cloudformation/network-stack.yaml
      parameters_file: cloudformation/config/network-parameters.json
      tags_file: cloudformation/config/tags.json
      environment: dev
    secrets: inherit

  data:
    name: Deploy Data Stack
    needs: network

    uses: ./.github/workflows/deploy-stack.yaml
    with:
      stack_name: data-stack-CloudMart
      template_file: cloudformation/data-stack.yaml
      parameters_file: cloudformation/config/data-parameters.json
      tags_file: cloudformation/config/tags.json
      environment: dev
    secrets: inherit
